### ISSUE TITLE
Where is instalation file?

### ISSUE THREAD

**Issue by ajbelle** [tobiasdiez/Jabref-FirefoxAddon#1]
I have searched standard Firefox install and https://hg.mozilla.org/mozilla-central. I cant find "Firefox central repository", to install and test your very useful code. Any hint?

**Comment by tobiasdiez** [comment]
Thank you for your interest. The problem is that Mozilla decided to stop supporting the AddOn-Builder platform and thus there is currently no way to run this addon. I'm working on a new version, but so far it is not ready yet (but hopefully soon...)

**Comment by teertinker** [comment]
Any status updates?

**Comment by tobiasdiez** [comment]
I have a working prototype which however still needs some clean-up. Hopefully, there will be a first release in a few weeks.

**Comment by tobiasdiez** [comment]
A very early version is now available. Just follow the [install instructions on the main page](https://github.com/tobiasdiez/Jabref-FirefoxAddon#installation-and-settings). It should work with the current Zotero and Firefox versions. If not, let me know. Any bug reports or feature requests are welcome!
