### ISSUE TITLE
Add more refined status information

### ISSUE THREAD

**Issue by koppor** [tobiasdiez/Jabref-FirefoxAddon#9]
When I visit https://www.uni-bamberg.de/pi/bereich/forschung/publikationen/13-03-lenhard-wirtz/ and press the "JR" button in the toolbar, I expect JabRef to open and the linked BibTeX file of the page to be imported in JabRef. However, nothing appears. I would have expected an error message at least. Currently, nothing happens here.

Possibly refs #4

**Comment by tobiasdiez** [comment]
Since there is no crawler registered for uni-bamberg.de, Zotero and consequently the add-on does not find the bib file.
But you are correct, there should be some visible clue that no bibliographic information is available, as #4 tracks.

**Comment by koppor** [comment]
Similar issue: When I open http://ieeexplore.ieee.org/xpl/articleDetails.jsp?reload=true&arnumber=528403 and click "JR", I can see Zotero importing it, then the new entry disappears and nothing happens. No entry in JabRef. What is the expected behavior? How can I trace errors?

**Comment by tobiasdiez** [comment]
Can you please open a new issue for this? Thanks.

I couldn't reproduce your error. For me the Addon works as expected on your site (i.e. open Jabref with one item waiting for import). For debugging, you can use the Browser console (Crtl + Shift + J).
